/**
 * Hardness — the closed-form robustness measure, ported to the browser.
 *
 * Port of butkeraites/hardness (MIT). The reference implementation is Python;
 * this is a reimplementation from its specification, checked against a golden
 * fixture generated by running that reference.
 *
 * The model: constraint j is  Σ_i a_ji·x_i − b_j ≤ 0, where every coefficient
 * a_ji is Uniform[aLo_ji, aHi_ji] and b_j is Uniform[bLo_j, bHi_j], all
 * independent. The signed violation Z_j is then a sum of independent, generally
 * non-identical uniforms plus a deterministic offset — a generalized
 * Irwin–Hall law whose CDF is an alternating inclusion–exclusion sum over the
 * 2^K subsets of its terms.
 *
 * Two scalars per constraint carry everything:
 *
 *   β_j = max(0, sup Z_j)                brittleness — the worst case
 *   I_j = ∫₀^{β_j} F_{Z_j}(t) dt         how much of the range is safe
 *   η_j = I_j / β_j  ∈ [0, 1]            hardness (:= 1 when β_j = 0)
 *
 * Two things a reimplementer gets wrong, both learned the hard way:
 *
 *   1. The lower integration limit term `[-τ_J]₊^{K+1}` is NOT optional. It is
 *      non-zero whenever τ_J < 0, which is common because L carries −bHi. Drop
 *      it and the probability mass on t < 0 — the *satisfied* region — leaks
 *      into the integral and inflates η.
 *   2. Cost is Θ(2^K) per constraint. Past K ≈ 12 the alternating sum also
 *      starts cancelling catastrophically; no implementation is trustworthy
 *      beyond ~8 significant digits there, the Python reference included.
 *
 * On that second point: compensated (Neumaier) summation was tried here and
 * did NOT help — measured 5.3e-11 → 8.2e-11 relative agreement at K = 15. The
 * dominant error is not accumulation order but `posPow` itself, which
 * amplifies the relative error of (t − τ) by a factor of K before anything is
 * summed. Compensation cannot recover digits that were never computed. The
 * simple loop is kept, and the test tolerances say what the formula actually
 * delivers rather than what one wishes it did.
 */

const MAX_K = 20

/** Factorials up to MAX_K + 1; beyond that the 2^K loop is the binding limit
 *  anyway, so exact integer factorials are enough. */
const FACT = (() => {
  const f = [1]
  for (let i = 1; i <= MAX_K + 2; i++) f.push(f[i - 1] * i)
  return f
})()

const clamp01 = v => (v < 0 ? 0 : v > 1 ? 1 : v)
const posPow = (u, k) => (u > 0 ? u ** k : 0)

/**
 * Turn one constraint's interval box and a fixed decision vector into the law
 * of its signed violation.
 *
 * Terms with zero width are deterministic and must be folded into a scalar
 * offset rather than modelled as degenerate uniforms — an earlier version of
 * the reference did the latter and produced η outside [0,1].
 */
export function buildDistribution({ aLo, aHi, bLo, bHi }, x) {
  const n = x.length
  const lTerms = []
  const rTerms = []
  let qSum = 0

  for (let i = 0; i < n; i++) {
    // Multiply by x_i FIRST, then order the endpoints: a negative x_i swaps them.
    const u = aLo[i] * x[i]
    const v = aHi[i] * x[i]
    const p = Math.min(u, v)
    const q = Math.max(u, v)
    lTerms.push(p)
    rTerms.push(q - p)
    qSum += q
  }

  // The right-hand side enters as W ~ Uniform[−bHi, −bLo].
  lTerms.push(-bHi)
  const rb = bHi - bLo
  if (rb > 0) rTerms.push(rb)

  let offset = 0
  const l = []
  const r = []
  for (let i = 0; i < rTerms.length; i++) {
    if (rTerms[i] > 0) { l.push(lTerms[i]); r.push(rTerms[i]) }
    else offset += lTerms[i]
  }
  for (let i = rTerms.length; i < lTerms.length; i++) offset += lTerms[i]

  const betaSup = qSum - bLo
  const beta = Math.max(betaSup, 0)

  if (r.length === 0) return { degenerate: true, c: offset, K: 0, beta, betaSup }

  // The whole deterministic offset rides on the first random term.
  l[0] += offset
  return { degenerate: false, l, r, K: r.length, beta, betaSup }
}

/** The 2^K breakpoints of the piecewise polynomial, with inclusion–exclusion
 *  signs. Enumerated by bitmask so the subset sum is incremental. */
function knots(dist) {
  const { l, r, K } = dist
  const L = l.reduce((a, b) => a + b, 0)
  const taus = new Float64Array(1 << K)
  const signs = new Int8Array(1 << K)
  taus[0] = L
  signs[0] = 1
  for (let mask = 1; mask < (1 << K); mask++) {
    const low = mask & -mask                 // lowest set bit
    const idx = 31 - Math.clz32(low)
    taus[mask] = taus[mask ^ low] + r[idx]
    signs[mask] = -signs[mask ^ low]
  }
  let R = 1
  for (const w of r) R *= w
  return { taus, signs, L, R }
}

/** F_Z(t) — probability the violation is at most t. */
export function cdf(dist, t) {
  if (dist.degenerate) return t >= dist.c ? 1 : 0
  const { taus, signs, R } = dist._knots ?? (dist._knots = knots(dist))
  const K = dist.K
  let sum = 0
  for (let mask = 0; mask < taus.length; mask++) {
    sum += signs[mask] * posPow(t - taus[mask], K)
  }
  // Accumulate the whole sum first, divide once, then clamp.
  return clamp01(sum / (FACT[K] * R))
}

/** ∫₀^T F_Z(t) dt, exactly. */
export function integralF0T(dist, T) {
  if (dist.degenerate) return Math.max(0, T - Math.max(dist.c, 0))
  const { taus, signs, R } = dist._knots ?? (dist._knots = knots(dist))
  const K = dist.K
  let sum = 0
  for (let mask = 0; mask < taus.length; mask++) {
    sum += signs[mask] * (posPow(T - taus[mask], K + 1) - posPow(-taus[mask], K + 1))
  }
  return Math.max(0, sum / (FACT[K] * R * (K + 1)))
}

/** Per-constraint hardness, plus the pieces the demo displays. */
export function constraintHardness(constraint, x) {
  const dist = buildDistribution(constraint, x)
  const { beta } = dist
  if (beta <= 0) {
    return { eta: 1, beta: 0, integral: 0, expectedViolation: 0, pFeasible: 1, K: dist.K }
  }
  const integral = integralF0T(dist, beta)
  const eta = integral / beta
  return {
    eta,
    beta,
    integral,
    // E[Z⁺] — the expected amount by which this constraint is violated.
    expectedViolation: Math.max(beta - integral, 0),
    pFeasible: cdf(dist, 0),
    K: dist.K,
  }
}

/**
 * Hardness of a decision vector against the whole constraint set.
 *
 * The two modes share every per-constraint computation and differ only in how
 * they average — but that difference is enough to invert the ranking of
 * candidate solutions outright, which is the whole reason the demo shows both.
 *
 *   weighted    η = Σ_j w_j η_j                 (default w_j = 1/m)
 *   aggregated  η = 1 − Σ_j E[Z_j⁺] / Σ_j β_j   (a β-weighted mean of the η_j)
 */
export function hardness(constraints, x, { mode = 'weighted', weights = null, integer = false } = {}) {
  // Integrality needs no special mathematics — the randomness lives in the
  // coefficients, so an integer x is simply a fixed x. What the reference does
  // do is SNAP components already within 1e-9 of an integer, and score the
  // snapped vector.
  if (integer) x = x.map(v => (Math.abs(v - Math.round(v)) <= 1e-9 ? Math.round(v) : v))
  const per = constraints.map(c => constraintHardness(c, x))

  if (mode === 'aggregated') {
    const betaSum = per.reduce((a, p) => a + p.beta, 0)
    if (betaSum <= 0) return { eta: 1, per, betaSum: 0 }
    const violSum = per.reduce((a, p) => a + p.expectedViolation, 0)
    return { eta: clamp01(1 - violSum / betaSum), per, betaSum }
  }

  // The reference treats a weight vector that does not already sum to 1 as
  // relative and renormalizes it (numpy.isclose tolerance: |sum − 1| > 1.001e-5).
  let w = weights ?? per.map(() => 1 / per.length)
  const wSum = w.reduce((a, b) => a + b, 0)
  if (Math.abs(wSum - 1) > 1.001e-5 && wSum !== 0) w = w.map(v => v / wSum)
  const eta = per.reduce((a, p, j) => a + w[j] * p.eta, 0)
  // The reference's weighted path has no clamp and can return a value a few
  // ULPs above 1. Clamping here is a deliberate divergence, and the fixture
  // test accounts for it.
  return { eta: clamp01(eta), per, betaSum: per.reduce((a, p) => a + p.beta, 0) }
}

/* ------------------------------------------------------ competing measures */

/** Worst-case total violation. Ignores everything about the distribution
 *  between nominal and worst case, which is exactly its problem. */
export function brittleness(constraints, x) {
  return constraints.reduce((a, c) => a + buildDistribution(c, x).beta, 0)
}

/**
 * NVDIC (Cheng, Liu, Tang & Tan 2017) — normalized violation degree of the
 * interval constraint. Lower is more robust, so it is the mirror image of η.
 *
 * It compares the CENTRE of the interval-valued left-hand side against the
 * centre of the right-hand side, normalized by their magnitudes. Everything it
 * knows about a plan comes from those centres — which is precisely why it goes
 * to exactly zero the moment the nominal problem is feasible, and stays there.
 * On the microgrid case that is four of seven plans: it cannot rank them at all.
 */
export function nvdic(constraints, x) {
  const safeDiv = (num, den) => (den === 0 ? 0 : num / den)
  let total = 0
  for (const c of constraints) {
    let lo = 0
    let up = 0
    for (let i = 0; i < x.length; i++) {
      const u = c.aLo[i] * x[i]
      const v = c.aHi[i] * x[i]
      lo += Math.min(u, v)
      up += Math.max(u, v)
    }
    const gc = 0.5 * (lo + up)
    const bc = 0.5 * (c.bLo + c.bHi)
    total += Math.max(safeDiv(gc - bc, Math.abs(gc) + Math.abs(bc)), 0)
  }
  return total
}

/* --------------------------------------------------------------- sampling */

/** Deterministic PRNG so a visitor's "roll scenarios" is reproducible within a
 *  session and identical across reloads. mulberry32 — small, fast, adequate. */
export function rng(seed) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) >>> 0
    let t = a
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/**
 * Draw scenarios and measure what actually happens: how often the plan fails,
 * and by how much on average. This is the empirical counterpart the closed form
 * is supposed to predict — showing them converge is the demo's proof.
 */
export function simulate(constraints, x, { scenarios = 20000, seed = 99991 } = {}) {
  const rand = rng(seed)
  const shortfalls = new Float64Array(scenarios)
  let violated = 0
  let total = 0

  for (let s = 0; s < scenarios; s++) {
    // Shortfall is the SUM of positive violations across constraints, not the
    // largest one: two periods each short by 1 MW is a 2 MW problem, and
    // taking the max would report it as 1. Verified against the reference —
    // the max reading is 18% low on the all-solar plan.
    let shortfall = 0
    for (const c of constraints) {
      let z = -(c.bLo + rand() * (c.bHi - c.bLo))
      for (let i = 0; i < x.length; i++) {
        z += (c.aLo[i] + rand() * (c.aHi[i] - c.aLo[i])) * x[i]
      }
      if (z > 0) shortfall += z
    }
    shortfalls[s] = shortfall
    if (shortfall > 0) violated++
    total += shortfall
  }

  return {
    shortfalls,
    expectedShortfall: total / scenarios,
    violationRate: violated / scenarios,
    scenarios,
  }
}

/** Bin a sample for display. */
export function histogram(values, bins = 36) {
  let lo = Infinity
  let hi = -Infinity
  for (const v of values) { if (v < lo) lo = v; if (v > hi) hi = v }
  if (!(hi > lo)) return { bins: [], lo, hi, width: 0 }
  const width = (hi - lo) / bins
  const counts = new Array(bins).fill(0)
  for (const v of values) {
    const k = Math.min(bins - 1, Math.floor((v - lo) / width))
    counts[k]++
  }
  return {
    bins: counts.map((n, i) => [lo + (i + 0.5) * width, n / values.length / width]),
    lo, hi, width,
  }
}
